export type DashboardComponentType =
  | 'kpi_card'
  | 'bar_chart'
  | 'line_chart'
  | 'area_chart'
  | 'pie_chart'
  | 'scatter_chart'
  | 'map_chart'
  | 'geo_map';

export type FilterType = 'date_range' | 'category_select';

export interface LayoutConfig {
  sm: number; // grid columns on mobile out of 12
  md: number; // grid columns on tablet out of 12
  lg: number; // grid columns on desktop out of 12
}

export interface KPITrend {
  direction: 'up' | 'down' | 'neutral';
  label: string;
}

export interface ComponentConfig {
  xAxisKey?: string;
  yAxisKeys?: string[];
  stacked?: boolean;
  colors?: string[]; // Array of colors or fallback
  seriesColors?: Record<string, string>; // Map of series key to color
  kpiValue?: string;
  kpiTrend?: KPITrend;
  showAnomalies?: boolean;
  showTrendline?: boolean;
  mapType?: 'world' | 'india';
  maxDataPoints?: number;
  limitLabel?: string;
  error?: string;
}

export interface DashboardComponent {
  id: string;
  type: DashboardComponentType;
  title: string;
  description?: string;
  tab?: string; // Optional page/tab identifier to split into multiple views
  layout: LayoutConfig;
  config: ComponentConfig;
  seriesData: Record<string, any>[];
}

export interface DashboardFilter {
  id: string;
  type: FilterType;
  targetKeys: string[];
  label: string;
  options?: string[];
}

export interface MasterDashboardPayload {
  dashboardId: string;
  title: string;
  subtitle?: string;
  filters: DashboardFilter[];
  components: DashboardComponent[];
  tabOrder?: string[];
  isAutoGenerated?: boolean;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
  associatedPayload?: MasterDashboardPayload; // Optional link to a specific dashboard state
}

export interface SavedDashboardMeta {
  dashboardId: string;
  title: string;
  subtitle?: string;
  savedAt: string;
  prompt: string;
}

export interface ColumnProfile {
  name: string;
  type: 'numeric' | 'categorical' | 'date' | 'geographic';
  min?: any;
  max?: any;
  mean?: number;
  stdDev?: number;
  nullCount: number;
  uniqueValues: number;
  topValues?: string[];
  annotatedUsage?: string; // AI metadata annotations
}

export interface CalculatedField {
  name: string;
  formula: string;
  type: 'numeric' | 'categorical';
  description: string;
}

export interface InlineChartSpec {
  id: string;
  title: string;
  chartType: 'bar' | 'line' | 'area' | 'pie';
  xKey: string;
  yKeys: string[];
  data: Record<string, any>[];
  insight: string;
  sourceOfTruth: 'dashboard_definition' | 'dashboard_dataset' | 'knowledge_base' | 'screenshot_ocr';
}

export interface AnalystSubAnswer {
  id: string;
  questionText: string;
  answerText: string;
  answerType: 'single_kpi' | 'comparison' | 'list' | 'trend' | 'explanation' | 'unavailable';
  interpretation: string;
  headline?: string;
  contextExplanation?: string;
  kpiSpotlight?: { value: string; label: string; trend?: string; changePercent?: number; isPositive?: boolean; context?: string } | null;
  sourceElements?: any[];
  annotationBoxes?: any[];
  sourcesUsed: string[];
  externalContext?: { used: boolean; summary: string | null; verified: boolean } | null;
  inlineChart: InlineChartSpec | null;
  suggestedChart: InlineChartSpec | null;
}

export interface QAMessage {
  id?: string;
  role?: 'user' | 'analyst';
  content?: string;
  sender?: 'user' | 'system';
  text?: string;
  timestamp: string;
  queryDetails?: string; 
  chartData?: any[];
  chartType?: 'bar' | 'kpi' | 'table';
  kpiHighlight?: { value: string; label: string };
  sourcesUsed?: ('dashboard_dataset' | 'dashboard_definition' | 'knowledge_base' | 'filters' | 'screenshot' | 'external_knowledge')[];
  externalContext?: { used: boolean; summary: string | null; verified: boolean } | null;
  suggestedFollowUps?: string[];
  answerType?: 'single_kpi' | 'comparison' | 'list' | 'trend' | 'explanation' | 'unavailable';
  kpiSpotlight?: any;
  miniChartData?: any[] | null;
  answers?: AnalystSubAnswer[];
  headline?: string;
  contextExplanation?: string;
}

export interface DashboardReport {
  title: string;
  subtitle?: string;
  kpis: { title: string; value: string; trend?: string }[];
  charts: { title: string; type: string; metrics: string[]; xKey?: string; insights: string }[];
  filters: string[];
  overallSummary: string;
  prosAndCons: string;
}

export interface ElementReport {
  elementId: string;
  elementType: string;
  title: string | null;
  location: string;
  boundingBoxEstimate: { x: number; y: number; width: number; height: number };
  extractedValues: Record<string, any>;
  confidenceScore: number;
}

export interface DashboardIntelligenceReport {
  dashboardTitle: string;
  reportingPeriod: string | null;
  overallTheme: string;
  totalElements: number;
  elements: ElementReport[];
  criticalAlerts: string[];
  toplineInsight: string;
}

export interface DashboardKnowledgeBasePage {
  pageId: string;
  pageName: string;
  charts: {
    title: string;
    type: string;
    metrics: string[];
    values: Record<string, any>[];
    insights: string;
  }[];
  tables: {
    title: string;
    headers: string[];
    rows: any[][];
    summary?: string;
  }[];
  kpis: {
    title: string;
    value: string;
    trend?: string;
    unit?: string;
  }[];
  filters: {
    name: string;
    options: string[];
  }[];
}

export interface DashboardKnowledgeBase {
  dashboardId: string;
  pages: DashboardKnowledgeBasePage[];
  routes?: string[];
  dashboards?: string[];
}

export interface IngestedDashboard {
  id: string;
  url: string;
  pageTitle?: string;
  screenshotBase64?: string;
  thumbnailBase64?: string;
  structuredReport: DashboardIntelligenceReport;
  ingestedAt: string;
  qaHistory: QAMessage[];
  captures?: { captureIndex: number; scrollPosition: number; imageBase64: string; pageNumber?: number }[];
  tabsDetected?: { label: string; index: number }[];
  domTextData?: string[];
  svgData?: { svgIndex: number; labelItems: string[] }[];
  knowledgeBase?: DashboardKnowledgeBase;
}
